package co.surumene.wgl.api;

public enum BreedingFailureReason {
    CHROMOSOME_COUNT_MISMATCH,
    INSUFFICIENT_CROSS_PARENT_HOMOLOGY,
    COMPATIBILITY_POLICY_REJECTED,
    CONSTRAINT_UNSATISFIABLE,
    INVALID_PARENT_STRUCTURE,
    SAFETY_REJECTED
}
