name: build
on:
  push:
    branches: [ main, develop, 'feature/**' ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '25'
      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '9.1.0'
      - run: gradle clean build --no-daemon
      - uses: actions/upload-artifact@v4
        with:
          name: WonderfulGenomeLib
          path: wgl-plugin/build/libs/WonderfulGenomeLib-*.jar
